# -*- coding: utf-8 -*-
"""Hangamn_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11J5LAjp5ADI7lnusCdbLQDDwaNSqwbT2
"""

import random

def hangman():
    word_list = ["python", "hangman", "computer", "programming", "code"]
    chosen_word = random.choice(word_list).lower()
    guessed_letters = []
    tries = 6

    while tries > 0:
        guessed_word = ""
        for letter in chosen_word:
            if letter in guessed_letters:
                guessed_word += letter
            else:
                guessed_word += "_"

        if guessed_word == chosen_word:
            print("Congratulations! You guessed the word correctly.")
            break

        print("Word:", guessed_word)
        print("Tries left:", tries)
        guess = input("Guess a letter: ").lower()

        if guess.isalpha() and len(guess) == 1:
            if guess in guessed_letters:
                print("You've already guessed that letter. Try again.")
            elif guess in chosen_word:
                print("Good guess!")
                guessed_letters.append(guess)
            else:
                print("Wrong guess!")
                tries -= 1
                guessed_letters.append(guess)
        else:
            print("Invalid input. Please enter a single letter.")

    if tries == 0:
        print("Game over! The word was:", chosen_word)

hangman()